services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ravioli_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ravioli_password}
      POSTGRES_DB: ${POSTGRES_DB:-ravioli_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/ravioli/backend/data/oltp/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${LOCAL_DATA_PATH:-~/Documents/ravioli_local_data}:/local_data:ro
    ports:
      - "5432:5432"
    networks:
      - ravioli_net
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ravioli_net
    restart: always

  app:
    build: .
    container_name: app
    environment:
      - DB_HOST=postgres
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - .:/app
      - ${LOCAL_DATA_PATH:-~/Documents/ravioli_local_data}:/local_data:ro
    ports:
      - "8501:8501"
    depends_on:
      - postgres
      - ollama
    env_file:
      - .env
    networks:
      - ravioli_net
    restart: always

volumes:
  postgres_data:
  ollama_data:


networks:
  ravioli_net:
    driver: bridge
