/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline-variant": "#524343",
        "inverse-surface": "#ece0df",
        "on-error": "#690005",
        "on-primary": "#512124",
        "secondary-fixed": "#f9dcd9",
        "surface-container-highest": "#3a3333",
        "on-secondary-container": "#cdb2af",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary": "#3d2f00",
        "on-secondary-fixed": "#271816",
        "surface-container": "#241e1e",
        "tertiary-container": "#eac34a",
        "primary-fixed-dim": "#ffb3b5",
        "surface-bright": "#393939",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#7b4245",
        "on-primary-fixed": "#370c11",
        "tertiary-fixed": "#ffe089",
        "on-background": "#ece0df",
        "surface-container-high": "#2f2828",
        "background": "#171212",
        "on-primary-fixed-variant": "#6d373a",
        "surface-container-lowest": "#120d0d",
        "surface": "#131313",
        "primary-fixed": "#ffdada",
        "inverse-on-surface": "#362f2f",
        "secondary-container": "#584542",
        "surface-container-low": "#201a1a",
        "on-surface": "#ece0df",
        "surface-variant": "#3a3333",
        "inverse-primary": "#894e50",
        "on-secondary": "#3d2c2a",
        "surface-tint": "#ffb3b5",
        "on-tertiary-container": "#665000",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "outline": "#a38b88",
        "tertiary": "#ffe08c",
        "tertiary-fixed-dim": "#e9c24a",
        "on-secondary-fixed-variant": "#554240",
        "on-surface-variant": "#d7c2c1",
        "on-tertiary-fixed-variant": "#574400",
        "primary-container": "#ffb3b5",
        "secondary-fixed-dim": "#dbc0bd",
        "secondary": "#dbc0bd",
        "primary": "#ffdada",
        "surface-dim": "#171212"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "1.5rem",
        "scale-16": "3.5rem",
        "margin": "2rem",
        "scale-10": "2.5rem",
        "scale-8": "2rem"
      },
      fontFamily: {
        "headline-lg": ["Noto Serif"],
        "display-lg": ["Noto Serif"],
        "label-sm": ["Space Grotesk"],
        "headline-sm": ["Noto Serif"],
        "body-md": ["Manrope"],
        "title-lg": ["Manrope"],
        "label-md": ["Space Grotesk"],
        "body-lg": ["Manrope"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "400" }],
        "display-lg": ["57px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "title-lg": ["22px", { "lineHeight": "28px", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
