name: "🐛 Bug Report"
description: Report a bug.
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What's the issue?
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Steps to reproduce, expected vs actual behavior.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Python version, etc.
